#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

### by Sascha ###

set -o vi

# PATH 
export PATH=$PATH:~/.bin/

# Editor
export VISUAL=vim
export EDITOR="$VISUAL"

# Aliases
alias c='clear'
alias o="xdg-open $@"
